language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  app: packsmart
  skip_cleanup: true
  api_key:
    secure: TIB9rvtoVz2lmhm/W+bRq54Bo9vMX3xSLseLb06/kGJvbtMOkSpy/4yIjYZQAvCYe15kUFi+9lwL92dClBGCh3VAj6SdMY6cQrnK8hlB3nV31wh78JsNOjNCpHsh81vpDw8CGf8laL8n54lDpoaY2axKlC8pvAAEgsWQeubPU/+wzLZ5CSP7fKi7CHaqYAGG06KpjyXxDuF3UzR2BvHkKuyS2PYOXJCBMEgNGHg4ZHpDU1muqSXSJFnMz1IOR1pmO++Dux3qaijF/5F7DAvfTW8g0Ug/eDhJVWAcilselCiO9TNH+k5vDxHkbNB1OMyIBWXGTV1kfDaIoAAdpr0QEAZWwV8tc584RFSucJXncgfAOAIM/y9Dt1ijXH50egYe1tcqPorBZmJPqulD/68P+eWqZP5dxxJDVeEbAfD8jHKwgBSrexuli2RkOUCfs/FptIIr7WWlFlZSA29kHtfqmVaZztfuhptysPd3KbuvHnrrdn7LqnDDjRRGDHtwAkFwkBhoJ5wGtINpt1hvD06U0MJYMgeDGfWH7YvZYWAJTtbkiz/XdwyZjpTqEfOMGlEdsViWmvzST64Klkh5A6quYrcSa345vSGr4KRe5wde+tvExndfMTaVbpXYXWy68+krrfmG322QtjW/n5LEMh4nn+Z9S4frgt/qCNuOxUrlHrA=
  on: main
